/**
 * Waitlist domain model
 *
 * A WaitlistEntry represents a customer wanting to be notified if a slot
 * opens up for a given service at a given location, optionally with a
 * preferred staff member and a date range.
 */

import type { Timestamp } from "firebase/firestore";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type WaitlistStatus = "active" | "matched" | "expired" | "cancelled";

export type WaitlistEntry = {
  /** Firestore document ID */
  entryId: string;
  tenantId: string;
  locationId: string;
  /** The customer who joined the waitlist */
  userId: string;
  serviceId: string;
  /** Preferred staff member — null means any */
  staffId: string | null;
  /** Earliest acceptable date (stored as ISO date string "YYYY-MM-DD") */
  dateFrom: string;
  /** Latest acceptable date (stored as ISO date string "YYYY-MM-DD") */
  dateTo: string;
  status: WaitlistStatus;
  /** When the entry was created */
  createdAt: Timestamp;
  /** When the entry was last updated */
  updatedAt: Timestamp;
  /** If matched: the booking slot ID that became available */
  matchedSlotId: string | null;
  /** ISO timestamp when a notification was last sent for this entry */
  lastNotifiedAt: string | null;
};

/**
 * Input for joining a waitlist.
 * entryId is generated by the repository.
 */
export type JoinWaitlistInput = Omit<
  WaitlistEntry,
  "entryId" | "status" | "createdAt" | "updatedAt" | "matchedSlotId" | "lastNotifiedAt"
>;

/**
 * A reduced view of a WaitlistEntry used during slot-open matching.
 */
export type WaitlistMatchCandidate = {
  entryId: string;
  userId: string;
  tenantId: string;
  locationId: string;
  serviceId: string;
  staffId: string | null;
  dateFrom: string;
  dateTo: string;
  lastNotifiedAt: string | null;
};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export type WaitlistErrorCode =
  | "invalid-date-range"    // dateFrom > dateTo
  | "already-on-waitlist"   // user already has an active entry for this service/location
  | "not-found"             // entry does not exist
  | "permission-denied";    // caller can't modify this entry

export class WaitlistError extends Error {
  constructor(
    public readonly code: WaitlistErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "WaitlistError";
  }
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validate that dateFrom <= dateTo.
 * Dates are ISO date strings "YYYY-MM-DD".
 */
export function validateWaitlistDates(dateFrom: string, dateTo: string): void {
  if (dateFrom > dateTo) {
    throw new WaitlistError(
      "invalid-date-range",
      `dateFrom (${dateFrom}) must not be after dateTo (${dateTo})`,
    );
  }
}
