import type {
  DiscoveryCategory,
  DiscoveryRecentBooking,
  ServiceTypeCard,
} from "./model";

export const discoveryCategories: DiscoveryCategory[] = [
  { id: "all" },
  { id: "nails" },
  { id: "hair" },
  { id: "skin" },
  { id: "lashes" },
  { id: "brows" },
  { id: "massage" },
  { id: "makeup" },
  { id: "barber" },
  { id: "waxing" },
  { id: "spa" },
  { id: "injectables" },
  { id: "wellness" },
];

export const featuredDiscoverySalons: ServiceTypeCard[] = [
  {
    id: "luna-studio",
    tenantId: "tenant-luna",
    locationId: "loc-luna-zagreb",
    categoryId: "hair",
    categoryName: "Hair",
    serviceName: "Gloss + blowout",
    locationDisplayName: "Luna Studio · Zagreb",
    locationCity: "Zagreb",
    priceFrom: 2800,
    variantCount: 1,
    durationFrom: 60,
    serviceAverageRating: 4.9,
    serviceReviewCount: 128,
    locationAverageRating: 4.9,
    locationReviewCount: 128,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 45.815,
    locationLng: 15.9819,
    distanceMetres: null,
    isSaved: true,
    memberPoints: 100,
    popularityScore: 0.85,
  },
  {
    id: "atelier-glow",
    tenantId: "tenant-glow",
    locationId: "loc-glow-split",
    categoryId: "skin",
    categoryName: "Skin",
    serviceName: "Hydrating facial",
    locationDisplayName: "Atelier Glow · Split",
    locationCity: "Split",
    priceFrom: 4200,
    variantCount: 1,
    durationFrom: 60,
    serviceAverageRating: 4.8,
    serviceReviewCount: 96,
    locationAverageRating: 4.8,
    locationReviewCount: 96,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 43.5081,
    locationLng: 16.4402,
    distanceMetres: null,
    isSaved: false,
    memberPoints: null,
    popularityScore: 0.72,
  },
  {
    id: "the-polish-room",
    tenantId: "tenant-polish-room",
    locationId: "loc-polish-rijeka",
    categoryId: "nails",
    categoryName: "Nails",
    serviceName: "Signature gel manicure",
    locationDisplayName: "The Polish Room · Rijeka",
    locationCity: "Rijeka",
    priceFrom: 2200,
    variantCount: 1,
    durationFrom: 45,
    serviceAverageRating: 4.7,
    serviceReviewCount: 83,
    locationAverageRating: 4.7,
    locationReviewCount: 83,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: false,
    locationLat: 45.3271,
    locationLng: 14.4422,
    distanceMetres: null,
    isSaved: true,
    memberPoints: 50,
    popularityScore: 0.65,
  },
];

export const recentDiscoveryBookings: DiscoveryRecentBooking[] = [
  {
    id: "booking-1",
    salonName: "Atelier Glow",
    serviceName: "Hydrating facial",
    dateTimeLabel: "Fri, 15 Mar at 13:30",
    statusLabel: "Confirmed",
  },
  {
    id: "booking-2",
    salonName: "Luna Studio",
    serviceName: "Gloss + blowout",
    dateTimeLabel: "Mon, 18 Mar at 09:00",
    statusLabel: "Upcoming",
  },
];

/**
 * Personalised recommendations shown in the "Based on your taste" section.
 * In production this is replaced by a server-side ranked query using the user's
 * aesthetic tags and booking history. For dev/test we hard-code 4 salons
 * matching common categories (nails, lashes, brows, massage).
 */
export const recommendedDiscoverySalons: ServiceTypeCard[] = [
  {
    id: "nail-bar-hana",
    tenantId: "tenant-nail-hana",
    locationId: "loc-nail-hana-zagreb",
    categoryId: "nails",
    categoryName: "Nails",
    serviceName: "Gel-X extensions",
    locationDisplayName: "Nail Bar Hana · Zagreb",
    locationCity: "Zagreb",
    priceFrom: 1800,
    variantCount: 1,
    durationFrom: 90,
    serviceAverageRating: 4.9,
    serviceReviewCount: 214,
    locationAverageRating: 4.9,
    locationReviewCount: 214,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 45.815,
    locationLng: 15.9819,
    distanceMetres: null,
    isSaved: true,
    memberPoints: 75,
    popularityScore: 0.9,
  },
  {
    id: "lash-suite-mia",
    tenantId: "tenant-lash-mia",
    locationId: "loc-lash-mia-zagreb",
    categoryId: "lashes",
    categoryName: "Lashes",
    serviceName: "Classic lash set",
    locationDisplayName: "Lash Suite Mia · Zagreb",
    locationCity: "Zagreb",
    priceFrom: 3500,
    variantCount: 1,
    durationFrom: 90,
    serviceAverageRating: 5.0,
    serviceReviewCount: 87,
    locationAverageRating: 5.0,
    locationReviewCount: 87,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 45.815,
    locationLng: 15.9819,
    distanceMetres: null,
    isSaved: false,
    memberPoints: null,
    popularityScore: 0.78,
  },
  {
    id: "brow-studio-lena",
    tenantId: "tenant-brow-lena",
    locationId: "loc-brow-lena-split",
    categoryId: "brows",
    categoryName: "Brows",
    serviceName: "Lamination + tint",
    locationDisplayName: "Brow Studio Lena · Split",
    locationCity: "Split",
    priceFrom: 2400,
    variantCount: 1,
    durationFrom: 60,
    serviceAverageRating: 4.8,
    serviceReviewCount: 156,
    locationAverageRating: 4.8,
    locationReviewCount: 156,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 43.5081,
    locationLng: 16.4402,
    distanceMetres: null,
    isSaved: false,
    memberPoints: null,
    popularityScore: 0.61,
  },
  {
    id: "zen-massage-studio",
    tenantId: "tenant-zen-massage",
    locationId: "loc-zen-massage-zagreb",
    categoryId: "massage",
    categoryName: "Massage",
    serviceName: "Deep tissue 60 min",
    locationDisplayName: "Zen Massage Studio · Zagreb",
    locationCity: "Zagreb",
    priceFrom: 4500,
    variantCount: 1,
    durationFrom: 60,
    serviceAverageRating: 4.7,
    serviceReviewCount: 193,
    locationAverageRating: 4.7,
    locationReviewCount: 193,
    nextAvailableAt: null,
    isFullyBooked: false,
    primaryPhotoUrl: null,
    primaryPhotoSource: null,
    isBookableOnline: true,
    locationLat: 45.815,
    locationLng: 15.9819,
    distanceMetres: null,
    isSaved: false,
    memberPoints: null,
    popularityScore: 0.55,
  },
];