import type {
  DiscoveryCategory,
  DiscoveryRecentBooking,
  DiscoverySalonCard,
} from "./model";

export const discoveryCategories: DiscoveryCategory[] = [
  { id: "all" },
  { id: "nails" },
  { id: "hair" },
  { id: "skin" },
  { id: "lashes" },
  { id: "brows" },
  { id: "massage" },
  { id: "makeup" },
  { id: "barber" },
  { id: "waxing" },
  { id: "spa" },
  { id: "injectables" },
  { id: "wellness" },
];

export const featuredDiscoverySalons: DiscoverySalonCard[] = [
  {
    id: "luna-studio",
    tenantId: "tenant-luna",
    name: "Luna Studio",
    city: "Zagreb",
    categories: ["hair", "brows"],
    rating: 4.9,
    reviewCount: 128,
    priceFrom: 28,
    currency: "EUR",
    nextAvailableLabel: "Today 4:30 PM",
    featuredService: "Gloss + blowout",
    member: true,
    bookingEnabled: true,
    messageEnabled: true,
  },
  {
    id: "atelier-glow",
    tenantId: "tenant-glow",
    name: "Atelier Glow",
    city: "Split",
    categories: ["skin", "spa"],
    rating: 4.8,
    reviewCount: 96,
    priceFrom: 42,
    currency: "EUR",
    nextAvailableLabel: "Tomorrow 10:00 AM",
    featuredService: "Hydrating facial",
    member: false,
    bookingEnabled: true,
    messageEnabled: true,
  },
  {
    id: "the-polish-room",
    tenantId: "tenant-polish-room",
    name: "The Polish Room",
    city: "Rijeka",
    categories: ["nails", "wellness"],
    rating: 4.7,
    reviewCount: 83,
    priceFrom: 22,
    currency: "EUR",
    nextAvailableLabel: "Today 6:15 PM",
    featuredService: "Signature gel manicure",
    member: true,
    bookingEnabled: false,
    messageEnabled: false,
  },
];

export const recentDiscoveryBookings: DiscoveryRecentBooking[] = [
  {
    id: "booking-1",
    salonName: "Atelier Glow",
    serviceName: "Hydrating facial",
    dateTimeLabel: "Fri, 15 Mar at 13:30",
    statusLabel: "Confirmed",
  },
  {
    id: "booking-2",
    salonName: "Luna Studio",
    serviceName: "Gloss + blowout",
    dateTimeLabel: "Mon, 18 Mar at 09:00",
    statusLabel: "Upcoming",
  },
];